version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: deltareboqueDB
      POSTGRES_USER: deltareboque
      POSTGRES_PASSWORD: deltareboquepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./delta:/delta
      - ./project:/project
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:
